name: Generate Screenshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install X keyboard packages
        run: |
          sudo apt-get update
          sudo apt-get install -y x11-xkb-utils xkb-data
      - name: Run screenshot script
        run: |
          chmod +x scripts/headless_screenshot.sh
          ./scripts/headless_screenshot.sh
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot_*.png

